import React,{useEffect,useRef,useState} from 'react';
import {art} from './art.tsx';
import {rank} from '../../packages/ui/config.ts';
import type {View} from '../../packages/core/index.ts';
export function Pointer(){return <span className="tap-pointer" aria-hidden="true"><svg viewBox="0 0 40 48"><path d="M13 25V7q0-6 6-3v17l3-7q4-3 6 2l2 4q6 0 6 7l-2 14H16L6 30q-2-6 3-6z" fill="#fff3d2" stroke="#a67f3d" strokeWidth="2"/></svg></span>;}
export function SeatTimer({active,remaining,duration}:{active:boolean;remaining:number;duration:number}){return active?<span role="timer" className={'seat-timer'+(remaining<=5?' urgent':'')} style={{'--timer-progress':Math.max(0,Math.min(1,remaining*1000/duration))} as React.CSSProperties}>{remaining}s</span>:null;}
export function DealerTable({v,motion,container,active,localSeat}:{v:View;motion:boolean;active:boolean;localSeat:number;container:React.RefObject<HTMLDivElement|null>}){
 const [flights,setFlights]=useState<{x:number;y:number;id:number}[]>([]),[drawing,setDrawing]=useState(-1),[event,setEvent]=useState('idle');const previous=useRef<{match:string;phase:string;redeals:number}|null>(null);const observed=useRef({revealed:v.revealed,sars:v.history.length});
 useEffect(()=>{const old=observed.current;observed.current={revealed:v.revealed,sars:v.history.length};if(!old.revealed&&v.revealed)setEvent('reveal');else if(v.history.length>old.sars&&v.pile===0)setEvent('collection');else if(v.phase==='calling')setEvent('present');else setEvent('waiting');const t=setTimeout(()=>setEvent('waiting'),1300);return()=>clearTimeout(t);},[v.revealed,v.history.length,v.phase]);
 const reduced=!motion||globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 useEffect(()=>{if(!active)return;const old=previous.current;previous.current={match:v.matchId,phase:v.phase,redeals:v.redeals};if(old?.match===v.matchId&&old.phase===v.phase&&old.redeals===v.redeals)return;
 const table=container.current;if(!table)return;const bounds=table.getBoundingClientRect();const seats=[...table.querySelectorAll<HTMLElement>('[data-seat]')];
 if(!reduced&&v.phase!=='finished')setFlights(seats.flatMap(el=>{const target=el.getBoundingClientRect();return Array.from({length:v.phase==='calling'?5:8},(_,n)=>({x:target.left+target.width/2-bounds.left,y:target.top+target.height/2-bounds.top,id:Number(el.dataset.seat)*8+n}));}));
 const schedule:ReturnType<typeof setTimeout>[]=[];setDrawing(-1);if((!old||old.match!==v.matchId)&&v.opening){const rounds=v.opening.rounds;setDrawing(0);const indices=rounds.length>3?[0,1,rounds.length-1]:rounds.map((_,i)=>i);indices.slice(1).forEach((index,n)=>schedule.push(setTimeout(()=>setDrawing(index),(n+1)*(reduced?100:600))));schedule.push(setTimeout(()=>setDrawing(-1),indices.length*(reduced?100:600)));}setEvent('shuffle');schedule.push(setTimeout(()=>setEvent('waiting'),reduced?0:350));schedule.push(setTimeout(()=>setFlights([]),reduced?0:1600));return()=>schedule.forEach(clearTimeout);
 },[v.matchId,v.phase,v.redeals,reduced,active]);
 const state=!active?'idle':event==='shuffle'?'shuffle':flights.length?'deal':v.phase==='finished'?(v.scores[localSeat%2]>v.scores[(localSeat+1)%2]?'victory':'defeat'):event==='reveal'?'reveal':event==='collection'?'collection':v.phase==='calling'?'present':'waiting';
 return <><div className={'table-host dealer-state-'+state} data-dealer-state={state} aria-label="Decorative dealer, not a player"><img src={art('characters/dealer-seated.webp')} alt="Rung Club dealer host"/><small>{state==='deal'?'Dealing…':state==='shuffle'?'Shuffling…':state==='reveal'?'Rung revealed':state==='collection'?'Pile collected':'Dealer'}</small><span className="dealer-deck" aria-hidden="true"/></div><div className="deal-flights" aria-hidden="true">{flights.map(f=><i key={f.id} style={{'--flight-x':f.x+'px','--flight-y':f.y+'px',animationDelay:(f.id%8)*60+'ms'} as React.CSSProperties}/>)}</div>{drawing>=0&&v.opening&&<div className="opening-draw" role="status"><strong>{drawing===v.opening.rounds.length-1?'Highest card · caller selected':'Tied highest cards · draw again'}</strong><div>{v.opening.rounds[drawing]?.cards.map(p=><span key={p.seat} className={v.opening!.rounds[drawing].eligible.includes(p.seat)?'winner':''}>Seat {p.seat+1}<img src={art('house/cards/'+rank(p.card.rank)+p.card.suit+'.svg')} alt={rank(p.card.rank)+' of '+p.card.suit}/></span>)}</div><small>Seat {v.opening.winner+1} selects Rung{v.opening.rounds.length>1?' · '+v.opening.rounds.length+' draw rounds':''}</small></div>}</>;
}
