// @vitest-environment jsdom
import React from 'react';import {beforeEach,afterEach,it,expect,vi} from 'vitest';import {render,screen,fireEvent,cleanup} from '@testing-library/react';
vi.mock('../apps/web/auth.ts',()=>({configured:true,restoredIdentity:async()=>({uid:'member',isAnonymous:false,getIdToken:async()=> 'verified'}),logout:async()=>{},authMessage:(e:Error)=>e.message,guestLogin:async()=>({local:false}),emailLogin:async()=>{},socialLogin:async()=>{},resetPassword:async()=>{},secureSession:async()=>({token:'verified'}),protectAccount:async()=>{},removeIdentity:async()=>{}}));
vi.mock('../apps/web/account-protection.tsx',()=>({AccountProtection:()=> <section>Account protected</section>}));
vi.mock('../apps/web/table.ts',()=>({mountTable:()=>({destroy:()=>{}})}));
import {App} from '../apps/web/main.tsx';
const profile=(name:string)=>({user:{uid:'member',name},totals:{xp:0},stats:{matches:0,wins:0},history:[]});
beforeEach(()=>{localStorage.clear();sessionStorage.clear();localStorage.setItem('profile',JSON.stringify({name:'PreviousPlayer',xp:0,matches:0,wins:0}));vi.stubGlobal('fetch',vi.fn());});afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('restores the registered account name rather than Guest or another local player',async()=>{vi.mocked(fetch).mockResolvedValue(Response.json(profile('SeniorUsama')));render(<App/>);await screen.findByRole('button',{name:'Practice table'});expect(screen.getAllByText('SeniorUsama',{exact:true})).toHaveLength(2);expect(screen.queryByText('PreviousPlayer',{exact:true})).toBeNull();expect(screen.queryByLabelText('Choose your username')).toBeNull();});
it('requires unnamed registered members to choose a unique name, and can retry a conflict',async()=>{vi.mocked(fetch).mockResolvedValueOnce(Response.json(profile('Guest-member'))).mockResolvedValueOnce(Response.json({error:'That username is taken.'},{status:409})).mockResolvedValueOnce(Response.json(profile('Baazi_2')));render(<App/>);const input=await screen.findByLabelText('Username');expect(screen.queryByRole('button',{name:'Practice table'})).toBeNull();fireEvent.change(input,{target:{value:'Baazi'}});fireEvent.click(screen.getByRole('button',{name:'Take my seat'}));await screen.findByText('That username is taken.');expect(screen.queryByRole('button',{name:'Practice table'})).toBeNull();fireEvent.change(input,{target:{value:'Baazi_2'}});fireEvent.click(screen.getByRole('button',{name:'Take my seat'}));await screen.findByRole('button',{name:'Practice table'});expect(screen.getAllByText('Baazi_2',{exact:true})).toHaveLength(2);expect(JSON.parse(localStorage.getItem('profile')!).name).toBe('Baazi_2');});
it('keeps setup available when the profile service fails rather than claiming a saved name',async()=>{vi.mocked(fetch).mockRejectedValue(Error('Offline'));render(<App/>);await screen.findByText('Profile connection unavailable. Retry saving your username.');expect(screen.getByLabelText('Username')).toBeTruthy();expect(screen.queryByRole('button',{name:'Practice table'})).toBeNull();});
