// @vitest-environment jsdom
import React from 'react';import {beforeEach,afterEach,it,expect,vi} from 'vitest';import {render,screen,fireEvent,cleanup,act} from '@testing-library/react';
const identity=vi.hoisted(()=>({anonymous:false}));
vi.mock('../apps/web/auth.ts',()=>({configured:true,restoredIdentity:async()=>({uid:'member',isAnonymous:identity.anonymous,getIdToken:async()=> 'verified'}),logout:async()=>{},authMessage:(e:Error)=>e.message,guestLogin:async()=>({local:false}),emailLogin:async()=>{},socialLogin:async()=>{},resetPassword:async()=>{},secureSession:async()=>({token:'verified'}),protectAccount:async()=>{},removeIdentity:async()=>{}}));
vi.mock('../apps/web/account-protection.tsx',()=>({AccountProtection:()=> <section>Account protected</section>}));
vi.mock('../apps/web/table.ts',()=>({mountTable:()=>({destroy:()=>{}})}));
import {App} from '../apps/web/main.tsx';
const profile=(name:string)=>({user:{uid:'member',name},totals:{xp:0},stats:{matches:0,wins:0},history:[]});
beforeEach(()=>{identity.anonymous=false;localStorage.clear();sessionStorage.clear();localStorage.setItem('profile',JSON.stringify({name:'PreviousPlayer',xp:0,matches:0,wins:0}));vi.stubGlobal('fetch',vi.fn());});afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('restores the registered account name rather than Guest or another local player',async()=>{vi.mocked(fetch).mockResolvedValue(Response.json(profile('SeniorUsama')));render(<App/>);await screen.findByRole('button',{name:'Practice table'});expect(screen.getAllByText('SeniorUsama',{exact:true})).toHaveLength(1);expect(screen.queryByText('PreviousPlayer',{exact:true})).toBeNull();expect(screen.queryByLabelText('Choose your username')).toBeNull();});
it('requires unnamed registered members to choose a unique name, and can retry a conflict',async()=>{vi.mocked(fetch).mockResolvedValueOnce(Response.json(profile('Guest-member'))).mockResolvedValueOnce(Response.json({error:'That username is taken.'},{status:409})).mockResolvedValueOnce(Response.json(profile('Baazi_2')));render(<App/>);const input=await screen.findByLabelText('Username');expect(screen.queryByRole('button',{name:'Practice table'})).toBeNull();fireEvent.change(input,{target:{value:'Baazi'}});fireEvent.click(screen.getByRole('button',{name:'Take my seat'}));await screen.findByText('That username is taken.');expect(screen.queryByRole('button',{name:'Practice table'})).toBeNull();fireEvent.change(input,{target:{value:'Baazi_2'}});fireEvent.click(screen.getByRole('button',{name:'Take my seat'}));await screen.findByRole('button',{name:'Practice table'});expect(screen.getAllByText('Baazi_2',{exact:true})).toHaveLength(1);expect(JSON.parse(localStorage.getItem('profile')!).name).toBe('Baazi_2');});
it('does not assume a username is missing when the profile service fails',async()=>{vi.mocked(fetch).mockRejectedValueOnce(Error('Offline')).mockResolvedValueOnce(Response.json(profile('SeniorUsama')));render(<App/>);await screen.findByText('Unable to load your profile. Retry to check your saved username.');expect(screen.queryByLabelText('Username')).toBeNull();expect(screen.queryByRole('button',{name:'Practice table'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Retry profile'}));await screen.findByRole('button',{name:'Practice table'});expect(screen.queryByLabelText('Username')).toBeNull();});
it('never flashes username setup while an existing profile request is pending',async()=>{let resolve!:(response:Response)=>void;vi.mocked(fetch).mockImplementationOnce(()=>new Promise<Response>(r=>{resolve=r;}));render(<App/>);await screen.findByText('Checking your seat…');expect(screen.queryByLabelText('Username')).toBeNull();await act(async()=>{resolve(Response.json(profile('SeniorUsama')));});await screen.findByRole('button',{name:'Practice table'});expect(screen.queryByLabelText('Username')).toBeNull();});

it('a delayed guest profile checks onboarding before displaying the lobby',async()=>{identity.anonymous=true;let resolve!:(response:Response)=>void;vi.mocked(fetch).mockImplementationOnce(()=>new Promise<Response>(r=>{resolve=r;}));render(<App/>);await screen.findByText('Checking your seat…');expect(screen.queryByRole('button',{name:'Skip Tutorial'})).toBeNull();await act(async()=>{resolve(Response.json({...profile('Guest-member'),tutorialStatus:'not-started'}));});await screen.findByRole('button',{name:'Practice table'});expect(screen.getByRole('button',{name:'Skip Tutorial'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Skip Tutorial'}));expect(localStorage.getItem('onboarding:member')).toBe('skipped');});
it('linked guests and returning identities retain terminal onboarding state',async()=>{localStorage.setItem('onboarding:member','completed');vi.mocked(fetch).mockResolvedValue(Response.json({...profile('SeniorUsama'),tutorialStatus:'not-started'}));render(<App/>);await screen.findByRole('button',{name:'Practice table'});expect(screen.queryByRole('button',{name:'Skip Tutorial'})).toBeNull();});
