// @vitest-environment jsdom
import React from 'react';
import {it,expect,vi,afterEach} from 'vitest';
import {renderHook,act,render,cleanup} from '@testing-library/react';
import {tableEvents,DealerAnnouncements,useCardInput} from '../apps/web/gameplay.tsx';
import {guidedDeal} from '../packages/core/tutorial.ts';
import {call,view,type View} from '../packages/core/index.ts';
afterEach(()=>{cleanup();vi.useRealTimers();});
function sample(){return view(call(guidedDeal(),0,'H'),0);}
it('same-card double tap submits once, different card selects, swipe cancels and wrong turn cannot submit',()=>{const v=sample(),submit=vi.fn(),select=vi.fn();const {result,rerender}=renderHook(({state})=>useCardInput(state,0,true,submit,select),{initialProps:{state:v}});const [a,b]=v.legal;
 act(()=>{result.current.tap(a);result.current.tap(b);});expect(submit).not.toHaveBeenCalled();act(()=>result.current.tap(b));expect(submit).toHaveBeenCalledExactlyOnceWith(b);
 act(()=>{result.current.down({clientX:0,clientY:0} as any);result.current.move({clientX:20,clientY:0} as any);result.current.tap(a);result.current.tap(a);});expect(submit).toHaveBeenCalledTimes(1);
 rerender({state:{...v,turn:1}});act(()=>{result.current.tap(a);result.current.tap(a);});expect(submit).toHaveBeenCalledTimes(1);
});
it('confirmation preference disables quick play and revision changes invalidate previous tap',()=>{const v=sample(),submit=vi.fn();const {result,rerender}=renderHook(({state,quick})=>useCardInput(state,0,quick,submit,vi.fn()),{initialProps:{state:v,quick:false}});act(()=>{result.current.tap(v.legal[0]);result.current.tap(v.legal[0]);});expect(submit).not.toHaveBeenCalled();rerender({state:{...v,revision:v.revision+1},quick:true});act(()=>result.current.tap(v.legal[0]));expect(submit).not.toHaveBeenCalled();});
it('Open announces suit; Band hides caller-private trump until actual reveal',()=>{const state=guidedDeal(),before=view(state,0),after=view(call(state,0,'H'),0);expect(tableEvents(before,after,0,['You','A','B','C'])[0].text).toBe('Hearts ♥ is the Rung!');const hidden={...after,mode:'band',revealed:false} as View;expect(tableEvents(before,hidden,0,['You','A','B','C']).filter(e=>e.voiceKey!=='turn').map(e=>e.text)).toEqual(['Hidden Rung is sealed.']);expect(tableEvents(hidden,{...hidden,revealed:true},0,[])[0].text).toContain('Hearts');});
it('fifth event occurs only at completed fourth Sar; collection requires score transition',()=>{const a=sample(),b={...a,history:[[],[],[],[]],winners:[0,1,0,0],pile:4,senior:0,revision:a.revision+4};const events=tableEvents(a,b,0,[]);expect(events.map(e=>e.text)).toContain('Fifth Sar — first collection chance!');expect(events.some(e=>e.voiceKey==='collection')).toBe(false);expect(tableEvents(b,b,0,[])).toEqual([]);expect(tableEvents(b,{...b,history:[...b.history,[]],scores:[5,0],pile:0},0,[]).some(e=>e.text==='You collected the Sars!')).toBe(true);});
it('queue shows priority fifth event once and does not replay unchanged reconnect snapshot',()=>{vi.useFakeTimers();const a=sample(),b={...a,history:[[],[],[],[]],winners:[0,1,0,0],pile:4,senior:0,revision:a.revision+4};const ui=render(<DealerAnnouncements v={a} seat={0} names={[]}/>);ui.rerender(<DealerAnnouncements v={b} seat={0} names={[]}/>);expect(ui.getByText('Fifth Sar — first collection chance!')).toBeTruthy();act(()=>vi.advanceTimersByTime(1800));expect(ui.getByText("You're Senior!")).toBeTruthy();act(()=>vi.advanceTimersByTime(1800));ui.rerender(<DealerAnnouncements v={{...b}} seat={0} names={[]}/>);expect(ui.queryByRole('status')).toBeNull();});

it('rematch clears queued messages and a stale turn message expires when the turn changes',()=>{vi.useFakeTimers();const a=sample();const ui=render(<DealerAnnouncements v={{...a,turn:1}} seat={0} names={[]}/>);ui.rerender(<DealerAnnouncements v={{...a,revision:a.revision+1}} seat={0} names={[]}/>);expect(ui.getByText('YOUR TURN')).toBeTruthy();ui.rerender(<DealerAnnouncements v={{...a,turn:1,revision:a.revision+2}} seat={0} names={[]}/>);expect(ui.queryByRole('status')).toBeNull();ui.rerender(<DealerAnnouncements v={{...a,matchId:'new-match'}} seat={0} names={[]}/>);expect(ui.queryByRole('status')).toBeNull();});
