// @vitest-environment jsdom
import React from 'react';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
const a=vi.hoisted(()=>({guest:vi.fn(),email:vi.fn(),google:vi.fn(),reset:vi.fn()}));
vi.mock('../apps/web/auth.ts',()=>({guestLogin:a.guest,emailLogin:a.email,socialLogin:a.google,resetPassword:a.reset,authMessage:(e:Error)=>e.message}));
import {Login} from '../apps/web/login.tsx';
beforeEach(()=>{vi.resetAllMocks();a.guest.mockResolvedValue({local:true});a.email.mockResolvedValue({});a.google.mockResolvedValue({});a.reset.mockResolvedValue(undefined);});afterEach(cleanup);
function setup(){const enter=vi.fn();render(<Login onEnter={enter}/>);return enter;}
function emailForm(){fireEvent.click(screen.getByRole('button',{name:'Sign In with Email'}));fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'player@example.com'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'secret123'}});}
it('welcome hides credentials and provides guest, Google and form entry',()=>{setup();expect(screen.queryByLabelText('Password')).toBeNull();expect(screen.getByRole('button',{name:'Play as a Guest'})).toBeTruthy();expect(screen.getByRole('button',{name:'Continue with Google'})).toBeTruthy();});
it('guest enters using adapter local/cloud result',async()=>{const enter=setup();fireEvent.click(screen.getByRole('button',{name:'Play as a Guest'}));await waitFor(()=>expect(enter).toHaveBeenCalledWith(true));});
it('successful Google entry uses the existing provider',async()=>{const enter=setup();fireEvent.click(screen.getByRole('button',{name:'Continue with Google'}));await waitFor(()=>expect(enter).toHaveBeenCalledWith(false));expect(a.google).toHaveBeenCalledWith('google');});
it.each(['Sign-in cancelled.','Unable to reach sign-in.'])('provider error preserves the entrance: %s',async message=>{a.google.mockRejectedValue(Error(message));const enter=setup();fireEvent.click(screen.getByRole('button',{name:'Continue with Google'}));expect((await screen.findByRole('alert')).textContent).toContain(message);expect(enter).not.toHaveBeenCalled();});
it('email sign-in passes trimmed credentials and password visibility works',async()=>{const enter=setup();emailForm();fireEvent.click(screen.getByRole('button',{name:'Show password'}));expect(screen.getByLabelText('Password').getAttribute('type')).toBe('text');fireEvent.submit(screen.getByLabelText('Password').closest('form')!);await waitFor(()=>expect(enter).toHaveBeenCalledWith(false,undefined));expect(a.email).toHaveBeenCalledWith('player@example.com','secret123',false);});
it('incorrect password preserves input and never enters',async()=>{a.email.mockRejectedValue(Error('Check your email and password.'));const enter=setup();emailForm();fireEvent.submit(screen.getByLabelText('Password').closest('form')!);await screen.findByRole('alert');expect(enter).not.toHaveBeenCalled();expect((screen.getByLabelText('Email address') as HTMLInputElement).value).toBe('player@example.com');});
it('registration passes username to existing account reservation flow',async()=>{const enter=setup();fireEvent.click(screen.getByRole('button',{name:'Create Account'}));fireEvent.change(screen.getByLabelText('Username'),{target:{value:'Baazi_123'}});fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'new@example.com'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'secret123'}});fireEvent.submit(screen.getByLabelText('Password').closest('form')!);await waitFor(()=>expect(enter).toHaveBeenCalledWith(false,'Baazi_123'));expect(a.email).toHaveBeenCalledWith('new@example.com','secret123',true);});
it('invalid email and username fail browser constraints',()=>{setup();fireEvent.click(screen.getByRole('button',{name:'Create Account'}));fireEvent.change(screen.getByLabelText('Username'),{target:{value:'a!'}});fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'invalid'}});expect((screen.getByLabelText('Username') as HTMLInputElement).validity.valid).toBe(false);expect((screen.getByLabelText('Email address') as HTMLInputElement).validity.valid).toBe(false);});
it('reset requires an email and shows non-enumerating success',async()=>{setup();fireEvent.click(screen.getByRole('button',{name:'Sign In with Email'}));fireEvent.click(screen.getByRole('button',{name:'Forgot?'}));await screen.findByRole('alert');expect(a.reset).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'player@example.com'}});fireEvent.click(screen.getByRole('button',{name:'Forgot?'}));expect((await screen.findByRole('status')).textContent).toContain('If an account exists');});
it('slow authentication disables alternatives and suppresses duplicate submissions',async()=>{let resolve!:(v:unknown)=>void;a.guest.mockImplementation(()=>new Promise(r=>resolve=r));const enter=setup();const guest=screen.getByRole('button',{name:'Play as a Guest'});fireEvent.click(guest);fireEvent.click(guest);expect(a.guest).toHaveBeenCalledTimes(1);expect((screen.getByRole('button',{name:'Continue with Google'}) as HTMLButtonElement).disabled).toBe(true);expect(enter).not.toHaveBeenCalled();resolve({local:false});await waitFor(()=>expect(enter).toHaveBeenCalledWith(false));});
