// @vitest-environment jsdom
import React from 'react';import {it,expect,vi,beforeEach,afterEach} from 'vitest';import {render,screen,fireEvent,cleanup,within,waitFor} from '@testing-library/react';
vi.mock('../apps/web/table.ts',()=>({mountTable:()=>({destroy:()=>{}})}));
import {App} from '../apps/web/main.tsx';
beforeEach(()=>{localStorage.clear();sessionStorage.clear();localStorage.setItem('welcome','1');});afterEach(()=>cleanup());
function callRung(){for(let n=0;n<12;n++){fireEvent.click(screen.getByRole('button',{name:/^♣$/}));if(screen.getByRole('generic',{name:'Your hand'}).querySelectorAll('button').length===13)return;}throw Error('Unable to reach valid deal');}
it('first launch offers guest sign-in and then a lobby with lessons',async()=>{render(<App/>);expect(screen.getByRole('button',{name:/Play as a guest/})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/Play as a guest/}));expect(await screen.findByRole('button',{name:'Practice table'})).toBeTruthy();expect(screen.getByRole('button',{name:'Learn the art of Rung'})).toBeTruthy();});
it('practice is playable: choose trump, select a legal card, submit',async()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Play as a guest/}));await screen.findByRole('button',{name:'Practice table'});fireEvent.click(screen.getByRole('button',{name:'Practice table'}));await waitFor(()=>{if(screen.queryByText('CHOOSE YOUR RUNG'))callRung();expect(screen.getByText('Your turn')).toBeTruthy();},{timeout:5000});expect(screen.getByText('Your turn')).toBeTruthy();const hand=screen.getByRole('generic',{name:'Your hand'});const legal=hand.querySelector('button.legal') as HTMLButtonElement;expect(legal).toBeTruthy();fireEvent.click(legal);fireEvent.click(screen.getByRole('button',{name:'Play card →'}));expect(within(hand).getAllByRole('button')).toHaveLength(12);expect(document.querySelector('.plays .played')).toBeTruthy();});
it('guided tutorial uses the real staged deal and can skip',async()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Play as a guest/}));await screen.findByRole('button',{name:'Practice table'});fireEvent.click(screen.getByRole('button',{name:'Learn the art of Rung'}));fireEvent.click(screen.getByText('Begin dealing'));fireEvent.click(screen.getByRole('button',{name:'♥'}));expect(screen.getByText(/Follow the led suit/)).toBeTruthy();const hand=screen.getByRole('generic',{name:'Your hand'});const legal=[...hand.querySelectorAll('button.legal')];expect(legal.length).toBeGreaterThan(0);expect(hand.querySelector('.tutorial-card')?.getAttribute('aria-label')).toBe('K of clubs');fireEvent.click(screen.getByText('Skip Tutorial'));expect(screen.queryByText('Begin dealing')).toBeNull();expect(localStorage.getItem('onboarding:local')).toBe('skipped');});
it('settings and local profile persist without cloud claims',async()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Play as a guest/}));await screen.findByRole('button',{name:'Practice table'});fireEvent.click(screen.getByText('Profile'));fireEvent.change(screen.getByLabelText('Local display name'),{target:{value:'Usama'}});expect(JSON.parse(localStorage.getItem('profile')!).name).toBe('Usama');expect(screen.getByText(/Local practice progress lives/)).toBeTruthy();});
it('retired avatar selections fall back safely and secondary screens omit the lobby HUD',async()=>{localStorage.setItem('avatar','11');render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Play as a guest/}));await screen.findByRole('button',{name:'Practice table'});fireEvent.click(screen.getByRole('button',{name:'Profile'}));expect(document.querySelector('header')).toBeNull();const choices=document.querySelectorAll('.avatar-roster button');expect(choices).toHaveLength(6);expect(choices[0].getAttribute('aria-pressed')).toBe('true');expect(localStorage.getItem('avatar')).toBe('1');fireEvent.click(screen.getByRole('button',{name:'Back to lobby'}));expect(screen.getAllByRole('button',{name:'Settings'})).toHaveLength(1);});
