// @vitest-environment jsdom
import React from 'react';import {it,expect,vi,beforeEach,afterEach} from 'vitest';import {render,screen,fireEvent,cleanup,within} from '@testing-library/react';
vi.mock('../apps/web/table.ts',()=>({mountTable:()=>({destroy:()=>{}})}));
import {App} from '../apps/web/main.tsx';
beforeEach(()=>{localStorage.clear();localStorage.setItem('welcome','1');});afterEach(()=>cleanup());
it('first launch offers tutorial and skip; skip persists',()=>{localStorage.removeItem('welcome');render(<App/>);expect(screen.getByText('Learn to Play')).toBeTruthy();fireEvent.click(screen.getByText('Skip Tutorial'));expect(localStorage.getItem('welcome')).toBe('1');expect(screen.getByText('Practice table')).toBeTruthy();});
it('practice is playable: choose trump, select a legal card, submit',()=>{render(<App/>);fireEvent.click(screen.getByText('Practice table'));expect(screen.getByText('Choose your Rung')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/^♣$/}));expect(screen.getByText('Your turn')).toBeTruthy();const hand=screen.getByRole('generic',{name:'Your hand'});const legal=hand.querySelector('button.legal') as HTMLButtonElement;expect(legal).toBeTruthy();fireEvent.click(legal);fireEvent.click(screen.getByRole('button',{name:'Play card →'}));expect(within(hand).getAllByRole('button')).toHaveLength(12);expect(screen.getByText('Zain is thinking…')).toBeTruthy();});
it('scripted follow-suit tutorial isolates legal cards and can skip',()=>{render(<App/>);fireEvent.click(screen.getByText('Learn the art of Rung'));fireEvent.click(screen.getByText('Next lesson'));expect(screen.getByText(/Follow the suit led/)).toBeTruthy();const hand=screen.getByRole('generic',{name:'Your hand'});const legal=[...hand.querySelectorAll('button.legal')];expect(legal.length).toBeGreaterThan(0);expect(legal.every(c=>c.getAttribute('aria-label')?.includes('clubs'))).toBe(true);fireEvent.click(screen.getByText('Skip tutorial'));expect(screen.queryByText('Next lesson')).toBeNull();});
it('settings and local profile persist without cloud claims',()=>{render(<App/>);fireEvent.click(screen.getByText('◉ Your profile'));fireEvent.change(screen.getByLabelText('Local display name'),{target:{value:'Usama'}});expect(JSON.parse(localStorage.getItem('profile')!).name).toBe('Usama');expect(screen.getByText(/Local practice progress lives/)).toBeTruthy();});
