import {createMatch} from '../../packages/core/opening.ts';
import {clockFor,expireTurn,type Clock} from '../../packages/protocol/timing.ts';
import {bandEligible} from '../../packages/protocol/progression.ts';
// DEVELOPMENT ONLY. Bind loopback; never deploy this identity provider publicly.
import http from 'node:http';import {randomBytes} from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import {WebSocketServer,WebSocket} from 'ws';
import {create,view,type State} from '../../packages/core/index.ts';import {Session,type Command} from '../../packages/protocol/index.ts';import {choose,chooseTrump} from '../../packages/ai/index.ts';
const db=new DatabaseSync('local-dev.sqlite');db.exec('CREATE TABLE IF NOT EXISTS rooms(code TEXT PRIMARY KEY, data TEXT); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,uid TEXT);');
type Room={game:Session,seats:(string|null)[],ready:boolean[],names:string[],started:boolean,bots:boolean[],updated:number,votes:boolean[],deadline?:number,lastRevision?:number;clock?:Clock};const rooms=new Map<string,Room>();
for(const row of db.prepare('SELECT * FROM rooms').all() as {code:string,data:string}[]){try{const d=JSON.parse(row.data);const game=new Session(d.state);game.seq=d.seq;game.seen=new Map(d.seen);rooms.set(row.code,{...d,game});}catch{}}
const sockets=new Map<WebSocket,{uid:string,code:string,seat:number}>();const rates=new Map<string,{n:number,t:number}>();
function save(code:string,r:Room){r.clock=clockFor(r.game.state,r.started,r.clock,Date.now(),r.bots[r.game.state.turn]);r.deadline=r.clock?.deadline;r.updated=Date.now();db.prepare('INSERT OR REPLACE INTO rooms VALUES (?,?)').run(code,JSON.stringify({...r,game:undefined,state:r.game.state,seq:r.game.seq,seen:[...r.game.seen]}));}
function identity(req:http.IncomingMessage){const token=req.headers.cookie?.match(/(?:^|; )rung_dev=([a-f0-9]+)/)?.[1];if(!token)return null;return (db.prepare('SELECT uid FROM sessions WHERE token=?').get(token) as {uid:string}|undefined)?.uid||null;}
function broadcast(code:string){const r=rooms.get(code)!;for(const [ws,s]of sockets)if(s.code===code&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'state',code,seat:s.seat,started:r.started,deadline:r.deadline,duration:r.clock?.duration,serverNow:Date.now(),ready:r.ready,names:r.names,bots:r.bots,seq:r.game.seq[s.seat],view:view(r.game.state,s.seat)}));}
const pending=new Map<string,ReturnType<typeof setTimeout>>();
function advanceBots(code:string){clearTimeout(pending.get(code));const r=rooms.get(code);if(!r?.clock||!r.started||r.game.state.phase==='finished')return;
pending.set(code,setTimeout(()=>{const live=rooms.get(code);if(!live)return;try{if(expireTurn(live.game,live.clock)){save(code,live);broadcast(code);}advanceBots(code);}catch(e){console.error('Automatic validation failed',String(e));}},Math.max(0,r.clock.deadline-Date.now())));}
// Local development accounts intentionally have no trusted cloud XP. Band rooms cannot bypass the gate.
const localEligible=()=>bandEligible(0);
const server=http.createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');const send=(status:number,body:unknown)=>{res.writeHead(status);res.end(JSON.stringify(body));};const ip=req.socket.remoteAddress||'local',now=Date.now();let rate=rates.get(ip);if(!rate||now-rate.t>60000){rate={n:0,t:now};rates.set(ip,rate);}if(++rate.n>180)return send(429,{error:'Slow down'});if(req.headers.origin&&!/^http:\/\/(localhost|127\.0\.0\.1|terminal\.local)(:\d+)?$/.test(req.headers.origin))return send(403,{error:'Origin denied'});
if(req.url==='/api/session'&&req.method==='POST'){let uid=identity(req);if(!uid){const token=randomBytes(32).toString('hex');uid=randomBytes(12).toString('hex');db.prepare('INSERT INTO sessions VALUES (?,?)').run(token,uid);res.setHeader('Set-Cookie',`rung_dev=${token}; HttpOnly; SameSite=Strict; Path=/`);}return send(200,{uid,developmentOnly:true});}const uid=identity(req);if(!uid)return send(401,{error:'Development session required'});
let body:any={};try{let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>4096)return send(413,{error:'Too large'});}body=raw?JSON.parse(raw):{};}catch{return send(400,{error:'Invalid JSON'});}
if(req.url==='/api/rooms'&&req.method==='POST'){if(rooms.size>=100)return send(503,{error:'Local room capacity'});const mode=body.mode==='band'?'band':'open';if(mode==='band'&&!localEligible())return send(403,{error:'Band Rung unlocks at Level 5; development sessions have no cloud XP'});let code=body.quick?[...rooms].find(([,r])=>!r.started&&r.seats.includes(null)&&r.game.state.mode===mode)?.[0]:undefined;code=code||randomBytes(4).toString('hex').toUpperCase();if(!rooms.has(code))rooms.set(code,{game:new Session(createMatch(mode)),seats:[uid,null,null,null],names:['You','Open seat','Open seat','Open seat'],ready:[false,false,false,false],bots:[false,false,false,false],started:false,updated:now,votes:[false,false,false,false]});const r=rooms.get(code)!;if(!r.seats.includes(uid)){const i=r.seats.indexOf(null);r.seats[i]=uid;r.names[i]='Guest '+uid.slice(0,4);}save(code,r);return send(200,{code});}
if(req.url==='/api/join'&&req.method==='POST'){const code=String(body.code).toUpperCase(),r=rooms.get(code);if(!r)return send(404,{error:'Room not found'});if(!r.seats.includes(uid)){if(r.game.state.mode==='band'&&!localEligible())return send(403,{error:'Band Rung unlocks at Level 5'});if(r.started)return send(409,{error:'Match started'});const i=r.seats.indexOf(null);if(i<0)return send(409,{error:'Room full'});r.seats[i]=uid;r.names[i]='Guest '+uid.slice(0,4);save(code,r);}broadcast(code);return send(200,{code});}return send(404,{error:'Not found'});});
const wss=new WebSocketServer({noServer:true,maxPayload:4096});server.on('upgrade',(req,socket,head)=>{const uid=identity(req),url=new URL(req.url!,'http://localhost'),code=url.searchParams.get('code')||'',r=rooms.get(code),seat=r?.seats.indexOf(uid||'')??-1;if(!uid||seat<0||req.headers.origin&&!/^http:\/\/(localhost|127\.0\.0\.1|terminal\.local)(:\d+)?$/.test(req.headers.origin)){socket.destroy();return;}wss.handleUpgrade(req,socket,head,ws=>{sockets.set(ws,{uid,code,seat});broadcast(code);advanceBots(code);let count=0,last=Date.now();ws.on('message',data=>{try{if(Date.now()-last>1000){count=0;last=Date.now();}if(++count>12)throw Error('Rate limited');const c=JSON.parse(String(data));if(c.type==='ready'){if(r!.started)throw Error('Already started');r!.ready[seat]=true;}else if(c.type==='start'){if(r!.seats[0]!==uid||r!.started)throw Error('Host only');if(r!.seats.some((p,i)=>p&&!r!.ready[i]))throw Error('All humans must be ready');r!.seats.forEach((p,i)=>{if(!p){r!.bots[i]=true;r!.names[i]=['Hamza','Uzair','Zain','Ali'][i]+' · Bot';}});r!.started=true;}else if(c.type==='emote'){if(!['Well played','Good luck','Nice Sar'].includes(c.text))throw Error('Invalid emote');for(const [w,info] of sockets)if(info.code===code)w.send(JSON.stringify({type:'emote',seat,text:c.text}));return;}else if(c.type==='rematch'){if(r!.game.state.phase!=='finished')throw Error('Match not finished');r!.votes[seat]=true;if(r!.seats.every((p,i)=>!p||r!.votes[i])){r!.game=new Session(createMatch(r!.game.state.mode));r!.votes.fill(false);}}else{if(!r!.started)throw Error('Not started');if(expireTurn(r!.game,r!.clock)){save(code,r!);broadcast(code);advanceBots(code);}const receipt=r!.game.apply(seat,c);ws.send(JSON.stringify({type:'ack',...receipt}));}save(code,r!);broadcast(code);advanceBots(code);}catch(e){ws.send(JSON.stringify({type:'error',message:(e as Error).message}));}});ws.on('close',()=>sockets.delete(ws));});});
for(const [code,r] of rooms){if(r.started&&!r.clock)save(code,r);advanceBots(code);}
setInterval(()=>{for(const[code,r]of rooms)if(Date.now()-r.updated>86400000&&!([...sockets.values()].some(s=>s.code===code))){rooms.delete(code);db.prepare('DELETE FROM rooms WHERE code=?').run(code);}},60000).unref();server.listen(8787,'127.0.0.1',()=>console.log('Development authoritative server: http://127.0.0.1:8787'));
