import {test,expect,request} from '@playwright/test';import {WebSocket} from 'ws';
const base='http://127.0.0.1:8787';
test('four identities, readiness, redaction, invalid and duplicate commands, reconnect',async()=>{const clients=await Promise.all(Array.from({length:4},()=>request.newContext({baseURL:base})));for(const c of clients)expect((await c.post('/api/session')).ok()).toBe(true);const code=(await (await clients[0].post('/api/rooms',{data:{mode:'open'}})).json()).code;for(const c of clients.slice(1))expect((await c.post('/api/join',{data:{code}})).ok()).toBe(true);
const sockets:WebSocket[]=[];const views:any[]=[],errors:any[]=[],acks:any[]=[];for(let i=0;i<4;i++){const cookies=(await clients[i].storageState()).cookies.map(c=>c.name+'='+c.value).join('; ');const ws=new WebSocket(base.replace('http','ws')+'/socket?code='+code,{headers:{Cookie:cookies,Origin:base}});sockets.push(ws);ws.on('message',msg=>{const d=JSON.parse(String(msg));if(d.type==='state')views[i]=d;if(d.type==='error')errors.push(d);if(d.type==='ack')acks.push(d);});await new Promise<void>(r=>ws.on('open',()=>r()));}
await expect.poll(()=>views.filter(Boolean).length).toBe(4);for(const ws of sockets)ws.send(JSON.stringify({type:'ready'}));await expect.poll(()=>views[0]?.ready.every(Boolean)).toBe(true);sockets[0].send(JSON.stringify({type:'start'}));await expect.poll(()=>views[0]?.started).toBe(true);const caller=views[0].view.caller;const state=views[caller];const indicator='H';const command={matchId:state.view.matchId,type:'call',card:indicator,id:'test-call',seq:1,revision:state.view.revision};sockets[caller].send(JSON.stringify(command));await expect.poll(()=>views[0]?.view.phase).toBe('playing');expect(views[1].view.trump).toBe('H');expect(views[1].view.indicator).toBeNull();expect(views[1].view.hands).toBeUndefined();const revision=views[0].view.revision;sockets[caller].send(JSON.stringify(command));await expect.poll(()=>acks.length).toBe(2);expect(views[0].view.revision).toBe(revision);
sockets[(caller+1)%4].send(JSON.stringify({matchId:state.view.matchId,type:'play',card:views[1].view.hand[0].id,id:'forged',seq:1,revision}));await expect.poll(()=>errors.length).toBe(1);expect(views[0].view.revision).toBe(revision);sockets[2].close();const cookies=(await clients[2].storageState()).cookies.map(c=>c.name+'='+c.value).join('; ');const reconnect=new WebSocket(base.replace('http','ws')+'/socket?code='+code,{headers:{Cookie:cookies,Origin:base}});const restored=await new Promise<any>(r=>reconnect.once('message',m=>r(JSON.parse(String(m)))));expect(restored.seat).toBe(2);expect(restored.view.revision).toBe(revision);expect(restored.view.trump).toBe('H');expect(restored.deadline).toBe(views[0].deadline);expect(restored.duration).toBe(20000);reconnect.close();for(const ws of sockets)ws.close();for(const c of clients)await c.dispose();});
test('reject unauthenticated, malformed JSON and hostile origin',async({request})=>{expect((await request.post('/api/rooms',{data:{}})).status()).toBe(401);expect((await request.post('/api/session',{headers:{Origin:'https://evil.example'}})).status()).toBe(403);});

test('server denies Band rooms regardless of submitted XP or level',async()=>{const client=await request.newContext({baseURL:base});await client.post('/api/session');const r=await client.post('/api/rooms',{data:{mode:'band',xp:999999,level:99}});expect(r.status()).toBe(403);expect((await r.json()).error).toContain('Level 5');await client.dispose();});
test('authoritative timeout survives disconnect and reconnect, with a new stable deadline',async()=>{test.setTimeout(45000);const client=await request.newContext({baseURL:base});await client.post('/api/session');const {code}=await(await client.post('/api/rooms',{data:{mode:'open'}})).json();const cookies=(await client.storageState()).cookies.map(c=>c.name+'='+c.value).join('; ');const connect=()=>new WebSocket(base.replace('http','ws')+'/socket?code='+code,{headers:{Cookie:cookies,Origin:base}});let current:any;const ws=connect();ws.on('message',m=>{const d=JSON.parse(String(m));if(d.type==='state')current=d;});await new Promise<void>(r=>ws.on('open',()=>r()));ws.send(JSON.stringify({type:'ready'}));await expect.poll(()=>current?.ready[0]).toBe(true);ws.send(JSON.stringify({type:'start'}));await expect.poll(()=>current?.started&&current.view.turn===0,{timeout:10000}).toBe(true);const before=current.view.revision,deadline=current.deadline;expect(deadline-Date.now()).toBeGreaterThan(10000);ws.close();await new Promise<void>(r=>setTimeout(r,Math.max(0,deadline-Date.now())+1000));const restored=connect();const state=await new Promise<any>(r=>restored.once('message',m=>r(JSON.parse(String(m)))));expect(state.view.revision).toBeGreaterThan(before);expect(state.view.matchId).toBe(current.view.matchId);expect(state.deadline).not.toBe(deadline);expect(state.view.hands).toBeUndefined();restored.close();await client.dispose();});
