import {test as base,expect} from '@playwright/test';
import fs from 'node:fs';
const test=process.env.BROWSER_EXECUTABLE_PATH?base.extend({context:async({playwright},use)=>{const browser=await playwright.chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--single-process','--no-zygote','--disable-software-rasterizer']});const context=await browser.newContext({baseURL:'http://127.0.0.1:5173'});await use(context);await browser.close();}}):base;
const out='docs/art/qa-entrance';fs.mkdirSync(out,{recursive:true});
for(const [width,height] of [[1920,1080],[1366,768],[412,924],[390,844],[360,800],[844,390]])test(`entrance ${width}x${height}`,async({page})=>{
 await page.setViewportSize({width,height});await page.goto('/');await expect(page.getByRole('button',{name:'Play as a Guest'})).toBeVisible();await expect(page.getByLabel('Email address')).toHaveCount(0);await expect.poll(()=>page.locator('.entry-stage img').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);await expect(page.locator('.splash')).toHaveCount(0);await page.waitForTimeout(700);await page.screenshot({path:`${out}/${width}x${height}-welcome.png`,fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1)).toBe(true);
 for(const label of ['Play as a Guest','Continue with Google','Sign In with Email','Create Account']){const b=page.getByRole('button',{name:label,exact:true});await expect(b).toBeInViewport();expect((await b.boundingBox())!.height).toBeGreaterThanOrEqual(44);}
 await page.getByRole('button',{name:'Sign In with Email'}).click();await page.getByLabel('Email address').fill('player@example.com');await page.getByLabel('Password',{exact:true}).fill('secret123');await page.waitForTimeout(250);await page.screenshot({path:`${out}/${width}x${height}-email.png`,fullPage:true});
 await page.getByRole('button',{name:'All ways to play',exact:false}).click();await page.getByRole('button',{name:'Create Account',exact:true}).click();await page.getByLabel('Username').fill('Baazi_123');await page.waitForTimeout(250);await page.screenshot({path:`${out}/${width}x${height}-signup.png`,fullPage:true});
 if(width<=412){await page.setViewportSize({width,height:Math.round(height*.55)});await page.getByLabel('Password',{exact:true}).focus();await page.getByLabel('Password',{exact:true}).scrollIntoViewIfNeeded();await expect(page.getByLabel('Password',{exact:true})).toBeInViewport();await page.getByRole('button',{name:'Create account',exact:true}).scrollIntoViewIfNeeded();await expect(page.getByRole('button',{name:'Create account',exact:true})).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
});
