import {test as base,expect} from '@playwright/test';
import fs from 'node:fs';
const test=process.env.BROWSER_EXECUTABLE_PATH?base.extend({context:async({playwright},use)=>{const browser=await playwright.chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--single-process','--no-zygote','--disable-software-rasterizer']});const context=await browser.newContext({baseURL:'http://127.0.0.1:5173'});await use(context);await browser.close();}}):base;
const output='docs/art/qa-experience';fs.mkdirSync(output,{recursive:true});
for(const [name,width,height] of [['desktop',1440,1000],['portrait',390,844],['landscape',844,390]] as const){
 test(name+' first-time guided match, five-Sar collection and persistence',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height});await page.goto('/');await page.getByRole('button',{name:'Play as a Guest',exact:true}).click();
  await expect(page.getByText(/Welcome to Rung Club! Let's play your first hand/)).toBeVisible();const target=page.getByRole('button',{name:'Select Open Rung'}),pointer=target.locator('.tap-pointer');await expect(pointer).toBeVisible();const a=(await target.boundingBox())!,b=(await pointer.boundingBox())!;expect(b.x).toBeGreaterThanOrEqual(a.x);expect(b.x+b.width).toBeLessThanOrEqual(a.x+a.width);
  await page.screenshot({path:output+'/'+name+'-welcome.png',fullPage:true});await target.click();await expect(page.getByText(/Your partner sits opposite/)).toBeVisible();await page.getByRole('button',{name:'Begin dealing'}).click();await expect(page.locator('.hand button')).toHaveCount(5);await page.getByRole('button',{name:'♥',exact:true}).click();await expect(page.locator('.hand button')).toHaveCount(13);await expect(page.locator('[role=timer]')).toHaveCount(0);
  await expect.poll(()=>page.locator('.hand img').evaluateAll(imgs=>imgs.every(img=>(img as HTMLImageElement).naturalWidth>0))).toBe(true);await expect(page.locator('.deal-flights i')).toHaveCount(0);await page.screenshot({path:output+'/'+name+'-guided-table.png',fullPage:true});for(const label of ['K of clubs','2 of clubs','A of hearts','K of hearts','Q of hearts']){const card=page.getByRole('button',{name:label,exact:true});await expect(card).toHaveClass(/tutorial-card/);await card.scrollIntoViewIfNeeded();await card.click();await page.getByRole('button',{name:'Play card →',exact:true}).click();await expect(page.locator('.hand .tutorial-card').or(page.getByText(/Well played! Five Sars collected/))).toBeVisible({timeout:10000});}
  await expect(page.getByText(/Well played! Five Sars collected/)).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('profile')!).xp)).toBe(0);await page.screenshot({path:output+'/'+name+'-tutorial-complete.png',fullPage:true});await page.getByRole('button',{name:'Play Open Rung',exact:true}).click();await page.reload();await expect(page.locator('.lobby')).toBeVisible();await expect(page.getByRole('button',{name:'Skip Tutorial',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('onboarding:local'))).toBe('completed');expect(errors).toEqual([]);
 });
}
test('skip is immediate at lobby and table; Band lock cannot be selected below Level 5',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Play as a Guest'}).click();await page.getByRole('button',{name:'Skip Tutorial'}).click();await page.reload();await expect(page.getByRole('button',{name:'Skip Tutorial'})).toHaveCount(0);await page.getByRole('button',{name:'Select Band Rung'}).click();await expect(page.getByRole('dialog',{name:'Band Rung locked'})).toBeVisible();await page.screenshot({path:output+'/portrait-band-locked.png',fullPage:true});await page.getByRole('button',{name:'Back to the lobby'}).click();await page.getByRole('button',{name:'Learn the art of Rung'}).click();await page.getByRole('button',{name:'Skip Tutorial'}).click();await expect(page.locator('.lobby')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('profile')!).xp)).toBe(0);});
test('reduced motion disables decorative flights and pointer follows a resized control',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await page.getByRole('button',{name:'Play as a Guest'}).click();await page.setViewportSize({width:320,height:640});const target=page.locator('.mode-tile.open');const pointer=target.locator('.tap-pointer');await expect(pointer).toBeVisible();expect(await pointer.evaluate(el=>getComputedStyle(el).animationName)).toBe('none');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await target.click();await page.getByRole('button',{name:'Begin dealing'}).click();await expect(page.locator('.deal-flights i')).toHaveCount(0);});
test('opening draw overlay clears when calling advances, including interrupted animation',async({page})=>{await page.addInitScript(()=>localStorage.setItem('welcome','1'));await page.goto('/');await page.getByRole('button',{name:'Play as a Guest'}).click();await page.getByRole('button',{name:'Practice table'}).click();await expect(page.locator('.opening-draw')).toBeVisible();if(await page.getByRole('button',{name:'♥',exact:true}).isVisible())await page.getByRole('button',{name:'♥',exact:true}).click();await expect(page.locator('.hand button')).toHaveCount(13);await expect(page.locator('.opening-draw')).toHaveCount(0);});
