import {test as base,expect} from '@playwright/test';
import fs from 'node:fs';
const test=process.env.BROWSER_EXECUTABLE_PATH?base.extend({context:async({playwright},use)=>{const browser=await playwright.chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--single-process','--no-zygote','--disable-software-rasterizer']});const context=await browser.newContext({baseURL:'http://127.0.0.1:5173'});await use(context);await browser.close();}}):base;
const out='docs/art/qa-gameplay';fs.mkdirSync(out,{recursive:true});
for(const [width,height] of [[1920,1080],[1366,768],[390,844],[360,800],[844,390],[932,430]])test(`${width}x${height} chooser, double tap and fifth Sar`,async({page})=>{
 await page.setViewportSize({width,height});await page.goto('/');await page.getByRole('button',{name:'Play as a Guest',exact:true}).click();await page.getByRole('button',{name:'Select Open Rung'}).click();await page.getByRole('button',{name:'Begin dealing'}).click();await expect(page.locator('.rung-banner')).toBeVisible();await expect(page.locator('.hand button')).toHaveCount(5);await page.waitForTimeout(1000);await page.screenshot({path:`${out}/${width}x${height}-rung.png`,fullPage:true});
 await page.getByRole('button',{name:'♥',exact:true}).click();await expect(page.locator('.hand button')).toHaveCount(13);await expect(page.getByText('Hearts ♥ is the Rung!')).toBeVisible();await page.locator('.hand').scrollIntoViewIfNeeded();await page.waitForTimeout(1700);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${out}/${width}x${height}-table.png`,fullPage:true});
 const king=page.getByRole('button',{name:'K of clubs',exact:true});await king.click();await expect(king).toHaveAttribute('aria-pressed','true');await king.click();await expect(page.locator('.hand button')).toHaveCount(12);await expect(king).toHaveCount(0);
 for(const label of ['2 of clubs','A of hearts','K of hearts']){const card=page.getByRole('button',{name:label,exact:true});await expect(card).toHaveClass(/tutorial-card/,{timeout:10000});await card.dblclick();}
 await expect(page.getByText('Fifth Sar — first collection chance!',{exact:true})).toBeVisible({timeout:10000});await page.screenshot({path:`${out}/${width}x${height}-fifth.png`,fullPage:true});
 const q=page.getByRole('button',{name:'Q of hearts',exact:true});await expect(q).toHaveClass(/tutorial-card/);await q.dblclick();await expect(page.getByText(/Well played! Five Sars collected/)).toBeVisible({timeout:10000});expect(await page.locator('.compact-hud>div').first().innerText()).toContain('5');
});
test('table preferences disable quick play without leaving the game',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Play as a Guest',exact:true}).click();await page.getByRole('button',{name:'Select Open Rung'}).click();await page.getByRole('button',{name:'Begin dealing'}).click();await page.getByRole('button',{name:'♥',exact:true}).click();await page.getByRole('button',{name:'Table settings'}).click();await page.getByLabel('Double-tap quick play').uncheck();await page.getByRole('button',{name:'Close table settings'}).click();const card=page.getByRole('button',{name:'K of clubs',exact:true});await card.dblclick();await expect(page.locator('.hand button')).toHaveCount(13);await expect(card).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Play card →'}).click();await expect(page.locator('.hand button')).toHaveCount(12);});

for(const [width,height] of [[1920,1080],[1366,768],[390,844],[360,800],[844,390],[932,430]])test(`${width}x${height} regular practice controls and hand`,async({page})=>{await page.addInitScript(()=>localStorage.setItem('welcome','1'));await page.setViewportSize({width,height});await page.goto('/');await page.getByRole('button',{name:'Play as a Guest',exact:true}).click();await page.getByRole('button',{name:'Practice table'}).click();for(let i=0;i<12;i++){await expect.poll(async()=>await page.locator('.hand button').count()===13||await page.getByRole('button',{name:'♣',exact:true}).isVisible()).toBe(true);if(await page.locator('.hand button').count()===13)break;await page.getByRole('button',{name:'♣',exact:true}).click();}await expect(page.locator('.hand button')).toHaveCount(13);await expect(page.locator('.hand button.legal').first()).toBeVisible({timeout:10000});await expect(page.locator('.deal-flights i')).toHaveCount(0);await page.locator('.hand button.legal').first().click();const play=page.getByRole('button',{name:'Play card →'});await expect(play).toBeEnabled();await play.scrollIntoViewIfNeeded();const a=(await play.boundingBox())!,b=(await page.locator('.hand').boundingBox())!;expect(a.y>=b.y+b.height-1||a.x>=b.x+b.width-1).toBe(true);expect(a.height).toBeGreaterThanOrEqual(44);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`${out}/${width}x${height}-practice.png`,fullPage:true});});
