import {test as base,expect} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
const test=process.env.BROWSER_EXECUTABLE_PATH?base.extend({context:async({playwright},use)=>{const browser=await playwright.chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--single-process','--no-zygote','--disable-software-rasterizer']});const context=await browser.newContext({baseURL:'http://127.0.0.1:5173'});await use(context);await browser.close();}}):base;
let server:ChildProcess;
test.beforeAll(async()=>{server=spawn(process.execPath,['apps/server/local.ts'],{stdio:'ignore'});await expect.poll(async()=>{try{return (await fetch('http://127.0.0.1:8787/api/session',{method:'POST'})).ok;}catch{return false;}}).toBe(true);});test.afterAll(()=>server?.kill());
test('server rejection restores selection; latency and repeated taps submit one play',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('welcome','1');const Native=WebSocket;(window as any).playSends=0;window.WebSocket=class extends Native{send(data:string){const d=JSON.parse(data);if(d.type!=='play'){super.send(data);return;}(window as any).playSends++;if((window as any).playSends===1){super.send(JSON.stringify({...d,card:'NOT_OWNED'}));return;}setTimeout(()=>super.send(data),350);}};});
 await page.goto('/');await page.getByRole('button',{name:'Play as a guest'}).click();await page.getByRole('button',{name:'Play Now →'}).click();await page.getByRole('button',{name:"I'm ready"}).click();await page.getByRole('button',{name:'Start casual table'}).click();for(let n=0;n<12;n++){await expect.poll(async()=>await page.locator('.hand button').count()===13||await page.getByRole('button',{name:'♣',exact:true}).isVisible()).toBe(true);if(await page.locator('.hand button').count()===13)break;await page.getByRole('button',{name:'♣',exact:true}).click();}
 const card=page.locator('.hand button.legal').first();await expect(card).toBeEnabled({timeout:10000});const name=await card.getAttribute('aria-label');await card.dblclick();await expect(page.getByRole('alert')).toContainText('Illegal card or turn');const selected=page.getByRole('button',{name:name!,exact:true});await expect(selected).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:'Play card →'})).toBeEnabled();await selected.dblclick();await expect(page.getByText('Sending card…')).toBeVisible();await page.locator('.hand').evaluate(el=>{const button=el.querySelector('button[aria-pressed="true"]') as HTMLButtonElement;button.click();button.click();});expect(await page.evaluate(()=>(window as any).playSends)).toBe(2);await expect(page.locator('.hand button')).toHaveCount(12);expect(await page.evaluate(()=>(window as any).playSends)).toBe(2);
});
