export type Suit='S'|'H'|'D'|'C';
export type Card={id:string,suit:Suit,rank:number};
export type Play={seat:number,card:Card,effective:number,trump:boolean,bhaag:boolean};
export type Policy={version:string,opening:number,superior:'opponent-only'|'always',aceChain:boolean,maxRedeals:number};
export const DEFAULT:Policy={version:'double-sar-v1-provisional',opening:5,superior:'opponent-only',aceChain:true,maxRedeals:64};
export type State={matchId:string,policy:Policy,mode:'open'|'band',phase:'calling'|'playing'|'finished',hands:Card[][],stock:Card[][],indicator:Card|null,caller:number,trump:Suit|null,revealed:boolean,turn:number,senior:number|null,trick:Play[],history:Play[][],winners:number[],pile:number,scores:number[],streakSeat:number|null,streak:number,lastAce:boolean,forceTrump:number|null,revision:number,redeals:number,result:string|null};
export const deck=():Card[]=>['S','H','D','C'].flatMap(s=>Array.from({length:13},(_,i)=>({id:s+(i+2),suit:s as Suit,rank:i+2})));
export function seeded(seed:number){return ()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
export function secureRandom(){const a=new Uint32Array(1);let v:number;do{crypto.getRandomValues(a);v=a[0];}while(v===0xffffffff);return v/0xffffffff;}
export function shuffled(random=secureRandom){const cards=deck();for(let i=51;i>0;i--){const j=Math.floor(random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}return cards;}
export function create(mode:State['mode']='open',random=secureRandom,policy=DEFAULT,caller=0):State{const d=shuffled(random);const hands=Array.from({length:4},()=>[] as Card[]),stock=Array.from({length:4},()=>[] as Card[]);let n=0;for(const count of [5,4,4])for(let step=0;step<4;step++){const seat=(caller-step+4)%4;const group=d.slice(n,n+=count);(count===5?hands:stock)[seat].push(...group);}return {matchId:crypto.randomUUID(),policy:{...policy},mode,phase:'calling',hands,stock,indicator:null,caller,trump:null,revealed:mode==='open',turn:caller,senior:null,trick:[],history:[],winners:[],pile:0,scores:[0,0],streakSeat:null,streak:0,lastAce:false,forceTrump:null,revision:0,redeals:0,result:null};}
export function call(s:State,seat:number,choice:string,random=secureRandom):State{if(s.phase!=='calling'||seat!==s.caller)throw Error('Not the caller');const next=structuredClone(s);if(next.mode==='band'){const c=next.hands[seat].find(c=>c.id===choice);if(!c)throw Error('Indicator must belong to opening five');next.trump=c.suit;next.indicator=c;}else{if(!['S','H','D','C'].includes(choice))throw Error('Invalid suit');next.trump=choice as Suit;}
for(let i=0;i<4;i++)next.hands[i].push(...next.stock[i]);next.stock=[[],[],[],[]];if(next.hands.some(h=>h.filter(c=>c.suit===next.trump).length>=7)){if(s.redeals>=s.policy.maxRedeals)throw Error('Redeal safety limit; start a fresh deal');const fresh=create(s.mode,random,s.policy,s.caller);fresh.matchId=s.matchId;fresh.redeals=s.redeals+1;fresh.revision=s.revision+1;return fresh;}
if(next.indicator)next.hands[seat]=next.hands[seat].filter(c=>c.id!==next.indicator!.id);next.phase='playing';next.revision++;return next;}
export function winning(plays:Play[]):Play|undefined{let best=plays[0];if(!best)return undefined;const led=best.card.suit;const category=(p:Play)=>p.trump?2:p.card.suit===led?1:0;for(const p of plays.slice(1)){if(category(p)>category(best)||(category(p)===category(best)&&p.card.suit===best.card.suit&&p.effective>best.effective))best=p;}return best;}
export function legal(s:State,seat:number):Card[]{if(s.phase!=='playing'||seat!==s.turn)return [];const hand=s.hands[seat];const led=s.trick[0]?.card.suit;const follow=hand.filter(c=>c.suit===led);if(follow.length){if(s.revealed&&led===s.trump)return superior(follow,winning(s.trick),s,seat);return follow;}if(!s.revealed||!s.trump||!led)return hand;const trumps=hand.filter(c=>c.suit===s.trump);const best=winning(s.trick);if(s.forceTrump===seat)return superior(trumps,best,s,seat).length?superior(trumps,best,s,seat):hand;if(best&&best.seat%2===seat%2&&s.policy.superior==='opponent-only')return hand;if(trumps.length)return superior(trumps,best,s,seat);return hand;}
function superior(cards:Card[],best:Play|undefined,s:State,seat:number){if(best?.trump&&(s.policy.superior==='always'||best.seat%2!==seat%2)){const higher=cards.filter(c=>c.rank>best.effective);if(higher.length)return higher;}return cards;}
export function canReveal(s:State,seat:number){return s.mode==='band'&&!s.revealed&&s.phase==='playing'&&s.turn===seat&&!!s.trick.length&&!s.hands[seat].some(c=>c.suit===s.trick[0].card.suit);}
export function reveal(s:State,seat:number):State{if(!canReveal(s,seat))throw Error('Reveal requires inability to follow suit on your turn');const n=structuredClone(s);n.revealed=true;if(n.indicator){n.hands[n.caller].push(n.indicator);n.indicator=null;}n.forceTrump=seat;n.revision++;return n;}
export function classifyBhaag(s:State,seat:number,c:Card,intent:boolean){return intent&&s.senior===seat&&s.trick.length===0&&c.rank!==14&&s.revealed&&c.suit!==s.trump;}
export function play(s:State,seat:number,id:string,intent=false):State{const card=legal(s,seat).find(c=>c.id===id);if(!card)throw Error('Illegal card or turn');const n=structuredClone(s);n.hands[seat]=n.hands[seat].filter(c=>c.id!==id);const downgraded=n.policy.aceChain&&n.trick.length===0&&n.senior===seat&&n.lastAce&&card.rank===14;n.trick.push({seat,card,effective:downgraded?2:card.rank,trump:n.revealed&&card.suit===n.trump,bhaag:classifyBhaag(s,seat,card,intent)});n.forceTrump=null;n.revision++;if(n.trick.length<4){n.turn=(seat+3)%4;return n;}
const best=winning(n.trick)!;n.history.push(n.trick);n.winners.push(best.seat);n.pile++;n.streak=n.streakSeat===best.seat?n.streak+1:1;n.streakSeat=best.seat;const sar=n.history.length;const collects=sar===13||(sar>=n.policy.opening&&n.streak>=2);if(collects){n.scores[best.seat%2]+=n.pile;n.pile=0;n.streak=0;n.streakSeat=null;}n.senior=best.seat;n.lastAce=best.card.rank===14;n.turn=best.seat;n.trick=[];if(sar===12&&n.mode==='band'&&!n.revealed){n.revealed=true;if(n.indicator){n.hands[n.caller].push(n.indicator);n.indicator=null;}}if(sar===13){n.phase='finished';const team=n.scores[0]>n.scores[1]?0:1;n.result=n.scores[team]===13?(team===n.caller%2?'Kot':'Goon Kot'):'Team '+(team+1)+' wins';}return n;}
export type View=Omit<State,'hands'|'stock'|'indicator'|'trump'> & {hand:Card[],counts:number[],trump:Suit|null,indicator:Card|null,legal:string[],canReveal:boolean};
export function view(s:State,seat:number):View{const {hands,stock,indicator,trump,...publicState}=structuredClone(s);return {...publicState,hand:hands[seat],counts:hands.map((h,i)=>h.length+stock[i].length+(indicator&&i===s.caller?1:0)),trump:s.revealed||seat===s.caller?trump:null,indicator:seat===s.caller?indicator:null,legal:legal(s,seat).map(c=>c.id),canReveal:canReveal(s,seat)};}
export function invariants(s:State){const cards=[...s.hands.flat(),...s.stock.flat(),...(s.indicator?[s.indicator]:[]),...s.history.flat().map(p=>p.card),...s.trick.map(p=>p.card)];if(cards.length!==52||new Set(cards.map(c=>c.id)).size!==52)throw Error('Card conservation');if(s.scores.reduce((a,b)=>a+b,0)+s.pile!==s.history.length)throw Error('Sar conservation');}
