import {create,deck,type State,type Card,type Play,DEFAULT} from './index.ts';
// Scripted, deterministic teaching fixtures. No private hands are passed to bots.
export function lesson(index:number):State{const d=deck();const card=(id:string)=>d.find(c=>c.id===id)!;const s=create('open',()=>.5);s.stock=[[],[],[],[]];s.trump='H';s.revealed=true;s.phase='playing';s.turn=0;s.senior=index>=3?0:null;s.revision=0;const used=new Set<string>();const take=(id:string)=>{used.add(id);return card(id);};
if(index===1){s.trick=[{seat:1,card:take('C13'),effective:13,trump:false,bhaag:false},{seat:2,card:take('C4'),effective:4,trump:false,bhaag:false},{seat:3,card:take('C3'),effective:3,trump:false,bhaag:false}];}
if(index===2){s.trick=[{seat:1,card:take('S14'),effective:14,trump:false,bhaag:false},{seat:2,card:take('S3'),effective:3,trump:false,bhaag:false},{seat:3,card:take('S4'),effective:4,trump:false,bhaag:false}];}
if(index===3){s.trick=[{seat:1,card:take('D13'),effective:13,trump:false,bhaag:false},{seat:2,card:take('D3'),effective:3,trump:false,bhaag:false},{seat:3,card:take('D4'),effective:4,trump:false,bhaag:false}];}
if(index>=4){for(let n=0;n<4;n++){const suit=['S','C','D','S'][n];const ids=[suit+(n+5),suit+(n+2),suit+(n+9),suit+(n+11)]; // Use remaining cards to maintain fixture uniqueness.
const group=d.filter(c=>!used.has(c.id)).slice(0,4);s.history.push(group.map((c,i)=>({seat:i,card:take(c.id),effective:c.rank,trump:c.suit==='H',bhaag:false})));}s.winners=[1,2,3,0];s.pile=4;s.streakSeat=0;s.streak=1;s.senior=0;}
const reserve=index===1?['C14','C2','H14']:index===2?['H14','H2','D2']:index===3?['D14','D2','H13']:['H14','H13','C14'];const own=reserve.filter(id=>!used.has(id)).map(take);let remaining=d.filter(c=>!used.has(c.id));const ownLength=13-s.history.length;while(own.length<ownLength){const i=index===2?remaining.findIndex(c=>c.suit!=='S'):0;const [c]=remaining.splice(i,1);own.push(take(c.id));}s.hands=[own,[],[],[]];for(let seat=1;seat<4;seat++){const count=13-s.history.length-(s.trick.some(p=>p.seat===seat)?1:0);s.hands[seat]=remaining.splice(0,count);}return s;}
